### ISSUE TITLE
File in source set wasn't found, Illegal Characters 🚓 🚨 

### ISSUE THREAD

**Issue by Notendoos** [Stefan-Espant/choices-choices-nuxt-datocms#1]
Ik zag dat je een aantal errors in je console had zitten. Ging met name om een file in de `sourceset`  in de `pages/index.vue` die nuxt niet kon ersolven. Na het aanpassen van de sourceset leek de build goed te gaan. Graag even nalopen, ik denk dat dit al je issues mogelijk zou moeten verhelpen :))

<img width="750" alt="Screenshot 2023-11-01 at 13 31 27" src="https://github.com/Stefan-Espant/choices-choices-nuxt-datocms/assets/17138832/6138bc36-e5fa-4dca-90a6-8a71181efdb9">

```html
 <source
    media="(max-width: 1400px)"
    srcset="./assets/Schermafbeelding_2023-10-23_om_21.42.21_vdwia0_c_scale,w_200.png 200w, <---
    "
>
```

Er morgen helaas geen comma's en special characters in je file URI zitten. Zorg er ook even voor dat je de files dan ook even de juiste naam meegeeft in je `/assets` folder.

**Comment by Stefan-Espant** [comment]
Dankjewel Maikel, hij staat nu live:
https://choices-choices-nuxt-datocms.vercel.app/
